# docker-compose.yml
version: '3.7'
services:
  web:
    image: 'yrzr/gitlab-ce-arm64v8:latest'
    restart: always
    hostname: 'https://source.sudox.app'
    container_name: gitlab-ce-arm64
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://source.sudox.app'
    ports:
      - '2204:22'
      - '8080:80'
      - '8443:443'
    volumes:
      - '~/gitlab/config:/etc/gitlab'
      - '~/gitlab/logs:/var/log/gitlab'
      - '~/gitlab/data:/var/opt/gitlab'
